apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:     # any key value pair | values must be base64 encoded
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
